import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>5/6A</title>)
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <h1 className="title">
          <Link href="/projet_1">
            <a>Projet 1</a>
          </Link>
        </h1>
        <h1 className="title">
          <Link href="/projet_2">
            <a>Projet 2</a>
          </Link>
        </h1>
        <h1 className="title">
          <Link href="/projet_3">
            <a>Projet 3</a>
          </Link>
        </h1>

      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenue à la classe 5/6 A!
        </h1>
        <Image className = "image" src = "/../public/piet.jpg" alt = "Logo PIET" width = "1563px" height = '774px'></Image>
      </main>

      <footer className={styles.footer}>
      Créé par le Vénérable M. Bloomfield
      </footer>
    </div>
  )
}
