import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>5/6A</title>)
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenue à la classe 5/6 A!
        </h1>
        <Image className = "image" src = "/../public/piet.jpg" alt = "Logo PIET" width = "1563px" height = '774px'></Image>
      </main>

      <footer className={styles.footer}>
      Créé par le Vénérable M. Bloomfield
      </footer>
    </div>
  )
}
